name: Api Tests CI

on:
  workflow_call:    
    inputs:
      dir:
        type: string
        description: "..."
        required: true
      dotnet-version: 
        type: string
        description: "..."
        default: 6.0.x
      os:
        type: string
        description: "..."
        required: true
    secrets:
      token:
        description: "..."
        required: true

jobs:
  test-results:
    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433
    steps:
      uses: ./.github/workflows/api_coverage
      secrets: inherit
      with:
        os: ${{ inputs.os }}
        dir: ${{ inputs.dir }}

      uses: ./.github/workflows/api_coverage
      secrets: inherit
