name: Api Tests CI

on:
  workflow_call:    
    inputs:
      dir:
        type: string
        description: "..."
        required: true
      dotnet-version: 
        type: string
        description: "..."
        default: 6.0.x
      os:
        type: string
        description: "..."
        required: true
    secrets:
      token:
        description: "..."
        required: true

jobs:
  api-coverage:
    uses: ./.github/workflows/api_coverage.yml
    secrets: inherit
    with:
      os: ${{ inputs.os }}
      dir: ${{ inputs.dir }}
