name: Run unit Tests
description: This project run project that has an assemly with Category=Unit

inputs:
  project-dir: 
    description: 'project directory'
    required: true
  category: 
    description: 'Type of the test'
    default: Unit

runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash
      continue-on-error: true 
      run: dotnet test ${{ inputs.project-dir }}
        --filter TestCategory=${{ inputs.category }}
        --logger:"trx;logfilename=Results.xml" 
        --configuration release
    