name: Build Dotnet Project
description: Hello!

inputs:
  dotnet-version: 
    description: 'Yay, dotnet version'
    required: false
    type: string
    default: 6.0.x

jobs:
  using: "composite"
  steps:
    - name: dotnet version
      run: echo dotnet version 6.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    