name: "API Tests & Analysis"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Api Coverage
      uses: Chingling152/my-financial-hub-api/api_coverage@feature/api-flow
      with:
        dir: ./src/FinancialHub/
        os: ${{ runner.os }}
      secrets:
        token: ${{ secrets.SONAR_TOKEN }}
        
    - uses: "./.github/workflows/api_test.yml"
