name: "API Tests & Analysis"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'


env:
  project-dir: ./src/FinancialHub/
  project-tests-dir: ./src/FinancialHub/ # for now it has no distiction
  project-tests-results-dir: ./src/FinancialHub/TestResult # for now it has no distiction

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: "./.github/workflows/api_test"
    - uses: "./.github/workflows/api_coverage_workflow"
