name: "API Release"

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - closed
    branches: 
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

jobs:
  releases:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test 2 
      run: echo ${{ github.event.pull_request.title }}
      shell: bash

    - name: Test 3
      run: echo ${{ github.event.pull_request.body }}
      shell: bash

    - name: Test 4
      run: echo "${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}"
      shell: bash

    - name: Get version
      env:
        BRANCH: ${{ github.event.pull_request.base.ref }}
      id: version
      run: echo "value=${BRANCH##*/}"	>> $GITHUB_OUTPUT

    - name: Get version
      run: echo ${{ steps.version.outputs.value }}