name: "Test"

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: false
        description: used to decide wich project will be tested

jobs: 
  tests:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/FinancialHub/

    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433

    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal  