name: "Base API Routine"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

jobs: 
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/FinancialHub/              
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: "./.github/workflows/api_build.yml"
      with:
        project-name: default