name: "API Tests & Analysis"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/api_coverage_workflow.yml
      with:
        dir: ./src/FinancialHub/
        
    # - uses: "./.github/workflows/api_test.yml"

    - uses: ./.github/actions/api-coverage-workflow
      with:
        os: ${{ runner.os }}
        sonar-token: ${{ secrets.SONAR_TOKEN }}
