name: "Base API Routine"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

jobs: 
  build:
    uses: "${{ github.event.repository.owner }}/${{ github.event.repository.name }}/.github/workflows/api_build.yml@feature/api-flow"
    with:
      project-name: default

  tests:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/FinancialHub/

    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433

    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
