name: Api Tests CI

on:
  workflow_call:    
    inputs:
      dir:
        type: string
        description: "..."
        required: true
      dotnet-version: 
        type: string
        description: "..."
        default: 6.0.x

jobs:
  api-coverage:
    uses: ./.github/workflows/api_coverage.yml
    secrets: inherit
    with:
      dir: ${{ inputs.dir }}
