name: "API Release"

on:
  workflow_dispatch:
  push:
    branches: 
      - 'release/**'
      #- 'main'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

jobs:
  releases:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test
      run: echo ${{ github.sha }}
      shell: bash

    - name: Test 2 
      run: echo ${{ github.event.head_commit.message }}
      shell: bash
