name: "Base API Routine"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/FinancialHub/*' 
      - 'src/FinancialHub/**'
  pull_request:
    branches: 
      - 'main'
      - 'release/**'
    #paths:
    #  - 'src/FinancialHub/*' 
    #  - 'src/FinancialHub/**'

jobs: 
  build:
    name: Build
    uses: "./.github/workflows/api_build.yml"
    with:
      project-name: default
  test:
    name: Tests
    needs: build
    uses: "./.github/workflows/api_test.yml"
    with:
      project-name: default
  