name: "Release Tests & Analysis"

on:
  pull_request:
    branches: 
      - 'release/**'
    paths:
      - 'src/api/*' 
      - 'src/api/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    uses: ./.github/workflows/tests_workflow.yml
    with:
      dir: ./src/api/
    secrets: inherit