name: "Main Tests & Analysis"

on:
  pull_request:
    branches: 
      - 'release/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["core", "auth"]
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.project }}
        uses: Chingling152/my-financial-hub-api@main/.github/workflows/tests_workflow.yml
        with:
          dir: ./src/api/${{ matrix.project }}
          secrets: inherit