name: "Matrix Tests & Analysis"

on:
  pull_request:
    branches: 
      - 'release/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        project: 
          - core
          - auth
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Project
        uses: ./.github/actions/build-dotnet-project
        with: 
          project-dir: ./src/api/${{ matrix.project }}
          dotnet-version: 6.0.x

      - name: Run Unit Tests
        uses: ./.github/actions/run-unit-test
        with: 
          project-dir: ./src/api/${{ matrix.project }}