name: "Matrix Tests & Analysis"

on:
  pull_request:
    branches: 
      - 'release/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433
    
    strategy:
      matrix:
        project: 
          - core
          - auth
    env:
      project-dir: ./src/api/${{ matrix.project }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup Project
        uses: ./.github/actions/build-dotnet-project
        with: 
          project-dir: ${{ env.project-dir }}
          dotnet-version: 6.0.x

      - name: Run Unit Tests
        uses: ./.github/actions/run-tests
        with: 
          project-dir: ${{ env.project-dir }}
          category: Unit
    
      - name: Run Integration Tests
        uses: ./.github/actions/run-tests
        with: 
          project-dir: ${{ env.project-dir }}
          category: Integration

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: ${{ matrix.project }} project test results
          action_fail: true
          files: "./tests/${{ matrix.project }}/**/TestResults/Results.xml"

  code_analysis:
    name: Code Analysis
    needs: tests
    uses: ./.github/workflows/coverage_report.yml
    secrets: inherit
    with:
      dir: ./src/api/
      dotnet-version: 6.0.x