name: Api Test Result
on:
  workflow_call:    
    inputs:
      dir:
        type: string
        required: true
      dotnet-version: 
        type: string
        default: 6.0.x

jobs:
  test_results:
    name: Code Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    services:
      sql-database: 
        image: mcr.microsoft.com/mssql/server:2019-latest    
        env: 
          SA_PASSWORD: "P@ssw0rd!"
          ACCEPT_EULA: "Y"
        ports: 
          - 1450:1433
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Project
        uses: ./.github/actions/build-dotnet-project
        with: 
          dir: ${{ inputs.dir }}
          dotnet-version:  ${{ inputs.dotnet-version }}

      - name: Run Tests
        continue-on-error: true 
        run: dotnet test 
          --logger:"trx;logfilename=Results.xml" 
          --configuration release
    
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          action_fail: true
          files: "**/TestResults/Results.xml"